baseURL = 'https://caminocreative.netlify.app/'
languageCode = 'en-us'
title = 'Camino Creative'
[taxonomies]
  contributor = 'contributors'
  client = 'clients'
  service = 'services'
  deliverables = 'deliverable'