backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: projects
    label: Projects
    label_singular: 'Project'
    folder: content/projects
    path: '{{slug}}/index'
    media_folder: 'gallery/'
    public_folder: 'gallery/'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'